/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          blue: '#00236f',
          orange: '#9d4300',
          lightBg: '#F0F4FF',
          darkText: '#202b3d',
          success: '#16A34A',
          warning: '#CA8A04',
          error: '#DC2626',
        },
        "primary-fixed-dim": "#b6c4ff",
        "on-tertiary-fixed": "#111c2d",
        "on-secondary-fixed": "#341100",
        "on-error-container": "#93000a",
        "surface-bright": "#faf8ff",
        "on-tertiary-container": "#a2adc4",
        "on-error": "#ffffff",
        "inverse-surface": "#2f3036",
        "inverse-on-surface": "#f1f0f7",
        "background": "#faf8ff",
        "primary-fixed": "#dce1ff",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdbca",
        "on-surface": "#1a1b21",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#3c475a",
        "surface-container-highest": "#e3e1e9",
        "surface-container-high": "#e9e7ef",
        "secondary": "#9d4300",
        "outline": "#757682",
        "surface-container-low": "#f4f3fa",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "primary": "#00236f",
        "outline-variant": "#c5c5d3",
        "primary-container": "#1e3a8a",
        "on-background": "#1a1b21",
        "on-surface-variant": "#444651",
        "surface-container": "#eeedf4",
        "secondary-fixed-dim": "#ffb690",
        "tertiary-container": "#364154",
        "surface-tint": "#4059aa",
        "tertiary": "#202b3d",
        "surface": "#faf8ff",
        "surface-dim": "#dad9e1",
        "on-primary-container": "#90a8ff",
        "on-secondary-container": "#5c2400",
        "tertiary-fixed-dim": "#bcc7de",
        "surface-variant": "#e3e1e9",
        "inverse-primary": "#b6c4ff",
        "on-secondary-fixed-variant": "#783200",
        "on-primary-fixed": "#00164e",
        "tertiary-fixed": "#d8e3fb",
        "on-primary-fixed-variant": "#264191",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "secondary-container": "#fd761a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-sm": "8px",
        "unit": "4px",
        "container-padding": "24px",
        "sidebar-width": "280px",
        "stack-lg": "32px",
        "gutter": "16px",
        "stack-md": "16px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "caption": ["12px", { "lineHeight": "16px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}

